let imagenesSlider = ["slider.jpg", "slider2.jpg", "slider3.jpg", "slider4.jpg",]

let productos = [

    {
        id: 0,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [32, 34, 35, 36, 38, 40],
        color: ["Azul claro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/vaquerosplisados1.jpg", "img/inventario/ropa/jeans/vaquerosplisados1.jpg", "img/inventario/ropa/jeans/vaquerosplisados2.jpg", "img/inventario/ropa/jeans/vaquerosplisados3.jpg"],
        precio: 2000,
        coleccion: "Primavera Verano",
        nombre: "Vaqueros plisados",
        destacados: true,
        genero: "femenino",
        descripcion: "Con una silueta oversize, los vaqueros de pernera ancha muestran detalles de pliegues en la parte delantera y una inesperada cintura elástica en la parte trasera. Están diseñados con cuatro bolsillos y anchas trabillas para el cinturón, y se abrochan con una cremallera y un botón, así como con el cierre de gancho Margiela. Se presentan en un acabado lavado, con dobladillos desgastados, para completar su corte extralargo."
    },
    {
        id: 1,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [32, 34, 35, 36, 38, 40],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/chinosskater1.jpg", "img/inventario/ropa/jeans/chinosskater2.jpg", "img/inventario/ropa/jeans/chinosskater3.jpg", "img/inventario/ropa/jeans/chinosskater4.jpg"],
        precio: 2400,
        coleccion: "Primavera Verano",
        nombre: "Chinos skater",
        destacados: false,
        genero: "femenino",
        descripcion: "Estos chinos se presentan en un corte oversize con pernera extralarga, cintura fruncida y pliegues. Las trabillas para el cinturón y los bolsillos laterales completan el look. Las Four stitches, emblemáticas de Maison Margiela, aparecen en la parte trasera; lo contrario a una etiqueta."
    },
    {
        id: 2,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [35, 36, 38, 40, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/pantalonchinoskater1.jpg", "img/inventario/ropa/jeans/pantalonchinoskater2.jpg", "img/inventario/ropa/jeans/pantalonchinoskater3.jpg", "img/inventario/ropa/jeans/pantalonchinoskater4.jpg"],
        precio: 2500,
        coleccion: "Otoño Invierno",
        nombre: "Pantalones chinos skater",
        destacados: false,
        genero: "masculino",
        descripcion: "Con cintura alta y pliegues, este pantalón chino skater ancho incluye además el gancho Margiela. La parte trasera es elástica, y cuenta con bolsillos laterales y traseros. Las Four stitches, tan emblemáticas de Maison Margiela, aparecen en la parte trasera; lo contrario a una etiqueta."
    },
    {
        id: 3,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [35, 36, 38, 40, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/pantalonconcanesu1.jpg", "img/inventario/ropa/jeans/pantalonconcanesu2.jpg", "img/inventario/ropa/jeans/pantalonconcanesu3.jpg", "img/inventario/ropa/jeans/pantalonconcanesu4.jpg"],
        precio: 2100,
        coleccion: "Otoño Invierno",
        nombre: "Pantalón con Canesú",
        destacados: false,
        genero: "masculino",
        descripcion: "Los pantalones skater chinos oversize tienen pliegues y el cierre de gancho de Margiela. Presentan un canesú, inspirado en las famosas manchas de tinta del test de Rorschach, con líneas arremolinadas que aluden a los emblemáticos canesúes del Oeste americano."
    },
    {
        id: 4,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [32, 36, 38, 40],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/pantalondegabardinadelana1.jpg", "img/inventario/ropa/jeans/pantalondegabardinadelana2.jpg", "img/inventario/ropa/jeans/pantalondegabardinadelana3.jpg", "img/inventario/ropa/jeans/pantalondegabardinadelana4.jpg"],
        precio: 2800,
        coleccion: "Otoño Invierno",
        nombre: "Pantalón de gabardina de lana",
        destacados: true,
        genero: "femenino",
        descripcion: "Los pantalones de gabardina de lana tienen la parte trasera ajustable, trabillas para el cinturón y bolsillos. Están inspirados en el fotógrafo alemán August Sander y su obra «Gente del siglo XX», y recrea la sensación vivida de la sastrería heredada aplicando una pátina brillante en la cintura, el dobladillo y los pliegues, como si los pantalones se hubieran llevado y atesorado durante décadas."
    },
    {
        id: 5,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [38, 40, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/pantalondelino1.jpg", "img/inventario/ropa/jeans/pantalondelino2.jpg", "img/inventario/ropa/jeans/pantalondelino3.jpg"],
        precio: 1600,
        coleccion: "Primavera Verano",
        nombre: "Pantalón de lino",
        destacados: true,
        genero: "masculino",
        descripcion: "Este pantalón de tela de lino de algodón, de corte oversize, tiene un pliegue delantero y bolsillos laterales. Las grandes trabillas para el cinturón y el cierre de botón y bragueta completan el look, junto con los dobladillos interiores divididos."
    },
    {
        id: 6,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [32, 34, 35, 36],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/pantalonescortosmultiusos1.jpg", "img/inventario/ropa/jeans/pantalonescortosmultiusos2.jpg", "img/inventario/ropa/jeans/pantalonescortosmultiusos3.jpg"],
        precio: 1700,
        coleccion: "Primavera Verano",
        nombre: "Pantalones cortos multiusos",
        destacados: false,
        genero: "femenino",
        descripcion: "Transformando una silueta en otra, el pantalón corto puede desplegarse y llevarse como un mono. Con la mitad superior doblada hacia abajo para un efecto de contraste, juega con el concepto de Anonymity of the lining, con la cremallera abierta en la parte trasera para una impresión de un corte que nos revela la etiqueta del numeric logo."
    },
    {
        id: 7,
        tipo: "Vestimenta",
        categoria: "Jeans y pantalones",
        talle: [32, 34, 35, 36, 38],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/jeans/pantalonesplisados1.jpg", "img/inventario/ropa/jeans/pantalonesplisados2.jpg", "img/inventario/ropa/jeans/pantalonesplisados3.jpg", "img/inventario/ropa/jeans/pantalonesplisados4.jpg"],
        precio: 1200,
        coleccion: "Primavera Verano",
        nombre: "Pantalones plisados",
        destacados: true,
        genero: "femenino",
        descripcion: "El pantalón de pernera ancha viene en una mezcla de algodón con detalles de pliegues exagerados que crean una silueta impactante y revelan el tejido interior en la cintura. El pantalón se completa con trabillas anchas, bolsillos y tapeta de cierre oculta para un aspecto más depurado. "
    },
    {
        id: 8,
        tipo: "Vestimenta",
        categoria: "Abrigos y chaquetas",
        talle: [30, 38, 48],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/abrigos/abrigodelana1.jpg", "img/inventario/ropa/abrigos/abrigodelana2.jpg", "img/inventario/ropa/abrigos/abrigodelana3.jpg"],
        precio: 2900,
        coleccion: "Otoño Invierno",
        nombre: "Abrigo de lana",
        destacados: true,
        genero: "femenino",
        descripcion: "Confeccionado en lana virgen y viscosa, el abrigo clásico nace del enfoque Exercise in Style de la colección SS25, una exploración de los iconos de la moda y el armario atemporal. Cortado a media pierna con una silueta recta, el abrigo sigue un diseño de botonadura sencilla con cuello de muesca y puños abotonados."
    },
    {
        id: 9,
        tipo: "Vestimenta",
        categoria: "Abrigos y chaquetas",
        talle: [30, 38, 48],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/abrigos/abrigodeviscosadelana1.jpg", "img/inventario/ropa/abrigos/abrigodeviscosadelana2.jpg", "img/inventario/ropa/abrigos/abrigodeviscosadelana3.jpg"],
        precio: 2450,
        coleccion: "Otoño Invierno",
        nombre: "Abrigo de viscosa de lana",
        destacados: false,
        genero: "masculino",
        descripcion: "Elaborado en lana viscosa, el abrigo presenta un cuello en contraste y un botón en la parte superior con una solapa oculta para un aspecto limpio. Una única abertura remata el diseño. Las four stitches blancas emblemáticas de Maison Margiela aparecen en la parte trasera; lo contrario de una marca."
    },
    {
        id: 10,
        tipo: "Vestimenta",
        categoria: "Abrigos y chaquetas",
        talle: [38, 44, 46, 48],
        color: ["Verde oliva"],
        stock: true,
        img: ["img/inventario/ropa/abrigos/cazadoraconcapucha1.jpg", "img/inventario/ropa/abrigos/cazadoraconcapucha2.jpg", "img/inventario/ropa/abrigos/cazadoraconcapucha3.jpg", "img/inventario/ropa/abrigos/cazadoraconcapucha4.jpg"],
        precio: 1850,
        coleccion: "Otoño Invierno",
        nombre: "Cazadora con capucha",
        destacados: true,
        genero: "femenino",
        descripcion: "El caban de algodón presenta una capucha utilitaria, así como grandes bolsillos funcionales en el pecho. Presenta lazos tonales en el cuello, que pueden utilizarse para ajustar el look, así como alrededor de los puños de las mangas para jugar con la silueta. Se añaden pespuntes decorativos para un enfoque fuera de lo común, con un lazo en la parte trasera de la capucha inspirado en la ropa de montaña."
    },
    {
        id: 11,
        tipo: "Vestimenta",
        categoria: "Abrigos y chaquetas",
        talle: [44, 46, 48],
        color: ["Negro lavado"],
        stock: true,
        img: ["img/inventario/ropa/abrigos/chaquetadealgodon1.jpg", "img/inventario/ropa/abrigos/chaquetadealgodon2.jpg", "img/inventario/ropa/abrigos/chaquetadealgodon3.jpg"],
        precio: 1350,
        coleccion: "Otoño Invierno",
        nombre: "Chaqueta de algodón con capucha",
        destacados: true,
        genero: "masculino",
        descripcion: "Con una capucha con cordón y un bolsillo canguro abotonado, esta chaqueta de algodón revestido cuenta con puños abotonados y un cordón en la cintura para un ajuste regulable. Tiene los hombros caídos y un ajuste relajado."
    },
    {
        id: 12,
        tipo: "Vestimenta",
        categoria: "Abrigos y chaquetas",
        talle: [32, 36, 44, 46, 48],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/abrigos/chaquetadelanasuave1.jpg", "img/inventario/ropa/abrigos/chaquetadelanasuave2.jpg"],
        precio: 1950,
        coleccion: "Otoño Invierno",
        nombre: "Chaqueta de lana suave",
        destacados: false,
        genero: "femenino",
        descripcion: "Esta chaqueta de lana con botonadura sencilla, cuello alto cosido y varios bolsillos presenta el tema de esnobismo invertido; el rechazo a la vestimenta burguesa convencional. "
    },
    {
        id: 13,
        tipo: "Vestimenta",
        categoria: "Abrigos y chaquetas",
        talle: [32, 36, 44],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/abrigos/gabardina1.jpg", "img/inventario/ropa/abrigos/gabardina2.jpg", "img/inventario/ropa/abrigos/gabardina3.jpg"],
        precio: 2150,
        coleccion: "Otoño Invierno",
        nombre: "Gabardina",
        destacados: false,
        genero: "masculino",
        descripcion: "Esta gabardina tiene un tratamiento usado. Está diseñada con una única abertura trasera, cuello clásico y puños abotonados, junto con una tapeta abotonada oculta para un look más minimalista. Las Four stitches, emblemáticas de Maison Margiela, aparecen en la parte trasera; lo contrario a una etiqueta."
    },
    {
        id: 14,
        tipo: "Vestimenta",
        categoria: "Faldas",
        talle: [32, 36, 44],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/faldas/faldaanonymityofthelining1.jpg", "img/inventario/ropa/faldas/faldaanonymityofthelining2.jpg", "img/inventario/ropa/faldas/faldaanonymityofthelining3.jpg"],
        precio: 1130,
        coleccion: "Otoño Invierno",
        nombre: "Falda Anonymity of the lining",
        destacados: true,
        genero: "femenino",
        descripcion: "Centrándose en el concepto de Anonymity of the lining de la Maison, la falda midi muestra un tejido en contraste con un detalle de lazo en la cintura como un guiño a la ropa interior. "
    },
    {
        id: 15,
        tipo: "Vestimenta",
        categoria: "Faldas",
        talle: [32, 36, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/faldas/faldanylon1.jpg", "img/inventario/ropa/faldas/faldanylon2.jpg.crdownload"],
        precio: 1090,
        coleccion: "Primavera Verano",
        nombre: "Falda de nylon",
        destacados: false,
        genero: "femenino",
        descripcion: "La falda por debajo de la rodilla viene en nylon semi transparente. Cuenta con una banda en la cintura y, en la espalda, una única abertura y un cierre de cremallera oculto para un aspecto limpio."
    },
    {
        id: 16,
        tipo: "Vestimenta",
        categoria: "Faldas",
        talle: [32, 36, 44, 46, 48],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/faldas/faltapantaloncortoacapas1.jpg", "img/inventario/ropa/faldas/faltapantaloncortoacapas2.jpg", "img/inventario/ropa/faldas/faltapantaloncortoacapas3.jpg", "img/inventario/ropa/faldas/faltapantaloncortoacapas4.jpg"],
        precio: 1300,
        coleccion: "Primavera Verano",
        nombre: "Falda pantalón corto a capas",
        destacados: false,
        genero: "femenino",
        descripcion: "Mostrando el concepto de Anonymity of the lining de la Maison, un enfoque lúdico de la confección, la falda tiene una capa interior con cintura de cordón, un panel central de corte crudo con trabillas para el cinturón y bolsillos, seguido de un pantalón corto de seda transparente enrollado en la rodilla. "
    },
    {
        id: 17,
        tipo: "Vestimenta",
        categoria: "Faldas",
        talle: [32, 36, 44, 46, 48],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/faldas/faltamiditafetan1.jpg", "img/inventario/ropa/faldas/faltamiditafetan2.jpg", "img/inventario/ropa/faldas/faltamiditafetan3.jpg", "img/inventario/ropa/faldas/faltamiditafetan4.jpg"],
        precio: 1300,
        coleccion: "Primavera Verano",
        nombre: "Falda midi tafetán",
        destacados: false,
        genero: "femenino",
        descripcion: "Creada en politafetán, la voluminosa falda midi presenta una parte delantera doblada hacia abajo, lo que redefine la silueta; se completa con las puntadas Work-in-progress de la Maison. La parte trasera luce un lazo y una cremallera abierta para reforzar la estética inacabada."
    },
    {
        id: 18,
        tipo: "Vestimenta",
        categoria: "Remeras y tops",
        talle: [32, 36, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/camisetasytops/bodydecuellovuelto1.jpg", "img/inventario/ropa/camisetasytops/bodydecuellovuelto2.jpg", "img/inventario/ropa/camisetasytops/bodydecuellovuelto3.jpg"],
        precio: 490,
        coleccion: "Primavera Verano",
        nombre: "Body de cuello vuelto",
        destacados: false,
        genero: "femenino",
        descripcion: "El body está confeccionado en punto de viscosa con cuello vuelto y manga larga con puños. Las Four stitches, tan emblemáticas de Maison Margiela, aparecen en la parte trasera; lo contrario a una etiqueta."
    },
    {
        id: 19,
        tipo: "Vestimenta",
        categoria: "Remeras y tops",
        talle: [32, 36, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/camisetasytops/bodyenjerseytecnico1.jpg", "img/inventario/ropa/camisetasytops/bodyenjerseytecnico2.jpg", "img/inventario/ropa/camisetasytops/bodyenjerseytecnico3.jpg"],
        precio: 690,
        coleccion: "Primavera Verano",
        nombre: "Body en jersey técnico",
        destacados: true,
        genero: "femenino",
        descripcion: "Este body de manga larga y cuello redondo está confeccionado en jersey técnico elástico para un acabado mínimo y sin costuras."
    },
    {
        id: 20,
        tipo: "Vestimenta",
        categoria: "Remeras y tops",
        talle: [32, 34, 36, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/camisetasytops/camisapolo1.jpg", "img/inventario/ropa/camisetasytops/camisapolo2.jpg", "img/inventario/ropa/camisetasytops/camisapolo3.jpg"],
        precio: 890,
        coleccion: "Primavera Verano",
        nombre: "Camisa polo",
        destacados: true,
        genero: "femenino",
        descripcion: "Esta camisa cropped, que reinterpreta una silueta deportiva retro, está confeccionada con cuello redondeado, manga corta y botones tonales. El corte compacto aporta un toque contemporáneo, mientras que el sutil brillo realza el tono vivo del tejido."
    },
    {
        id: 21,
        tipo: "Vestimenta",
        categoria: "Remeras y tops",
        talle: [32, 34, 36, 44, 46],
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/ropa/camisetasytops/topsolosunfaded1.jpg", "img/inventario/ropa/camisetasytops/topsolosunfaded2.jpg", "img/inventario/ropa/camisetasytops/topsolosunfaded3.jpg"],
        precio: 750,
        coleccion: "Primavera Verano",
        nombre: "Top polo sun-faded",
        destacados: false,
        genero: "femenino",
        descripcion: "En una edición limitada, este polo descolorido por el sol recuerda las prendas desgastadas naturalmente por el paso del tiempo. Inspirado en prendas de trabajo reales, presenta un acabado vintage que imita la pátina de la exposición al sol, lo que aporta textura a su confección ultraligera."
    },
    {
        id: 22,
        tipo: "Bolsos",
        categoria: "Bolsos",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/bolsos/5ACClassiqueMini1.jpg", "img/inventario/bolsos/5ACClassiqueMini2.jpg", "img/inventario/bolsos/5ACClassiqueMini3.jpg"],
        precio: 1500,
        coleccion: "Otoño Invierno",
        nombre: "Bolso 5AC Classique Mini",
        destacados: false,
        genero: "femenino",
        descripcion: "El 5AC classique mini, confeccionado en piel en flor, presenta asas superiores y correa de tono. Está adornado con la etiqueta del logotipo en la parte delantera. La emblemática línea 5AC toma su nombre de la palabra francesa «sac» (bolso). Interpreta el concepto de Anonymity of the lining de la Maison. Los remaches metálicos del bolso están cubiertos por piel a mano, y el metal solo está visible cuando es necesario para lograr un aspecto impecable. "
    },
    {
        id: 23,
        tipo: "Bolsos",
        categoria: "Bolsos",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/bolsos/BolsodemanopequeñoSnatched1.jpg", "img/inventario/bolsos/BolsodemanopequeñoSnatched2.jpg", "img/inventario/bolsos/BolsodemanopequeñoSnatched3.jpg"],
        precio: 1750,
        coleccion: "Otoño Invierno",
        nombre: "Bolso de mano pequeño Snatched",
        destacados: false,
        genero: "femenino",
        descripcion: "El bolso de mano Snatched pequeño está diseñado con un acabado texturizado, acabado metalizado y de charol para enfatizar sus arrugas. El bolso Snatched se presentó por primera vez en la colección Artisanal AW19. Su nombre procede de un término coloquial para indicar que algo «luce bien», pero también hace referencia a la forma en que se puede llevar este diseño. Este bolso unisex presenta una forma asimétrica que se inspira en el origami."
    },
    {
        id: 24,
        tipo: "Bolsos",
        categoria: "Bolsos",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/bolsos/DressageHobo1.jpg", "img/inventario/bolsos/DressageHobo2.jpg", "img/inventario/bolsos/DressageHobo3.jpg"],
        precio: 2000,
        coleccion: "Otoño Invierno",
        nombre: "Bolso dress age Hobo",
        destacados: false,
        genero: "femenino",
        descripcion: "La Maison lanza el bolso hobo Dress-age para SS25, diseñado en suave piel de becerro. Con un toque ecuestre, este bolso pequeño presenta un trabajo de cuero clásico y líneas refinadas, combinando un glamour inconsciente con un diseño gestual. Tiene forma trapezoidal con detalle de correa de doble uso en contraste. La base tachonada permite que el bolso se mantenga de pie, y el interior está adornado con el logotipo."
    },
    {
        id: 25,
        tipo: "Bolsos",
        categoria: "Bolsos",
        color: ["Azul"],
        stock: true,
        img: ["img/inventario/bolsos/GlamSlamhobopequeño1.jpg", "img/inventario/bolsos/GlamSlamhobopequeño2.jpg", "img/inventario/bolsos/GlamSlamhobopequeño3.jpg"],
        precio: 1650,
        coleccion: "Otoño Invierno",
        nombre: "Bolso glam slam Hobo pequeño",
        destacados: true,
        genero: "femenino",
        descripcion: "El bolso hobo Glam Slam pequeño está confeccionado en terciopelo acolchado. El Glam Slam debutó en el desfile SS18 y tiene un diseño acolchado que imita el matelassé, el estilo de los edredones cosidos a mano creado en Marsella, Francia. El concepto refleja la noción de unconscious glamour de la Maison y evoca su asociación con el confort, siguiendo el estudio de los rituales del vestir y viajar por todo el mundo."
    },
    {
        id: 26,
        tipo: "Bolsos",
        categoria: "Bolsos",
        color: ["Azul"],
        stock: true,
        img: ["img/inventario/bolsos/MochilamediumHightech1.jpg", "img/inventario/bolsos/MochilamediumHightech2.jpg", "img/inventario/bolsos/MochilamediumHightech3.jpg", "img/inventario/bolsos/MochilamediumHightech4.jpg"],
        precio: 1650,
        coleccion: "Otoño Invierno",
        nombre: "Mochila medium High tech",
        destacados: true,
        genero: "femenino",
        descripcion: "Esta mochila técnica está confeccionada en un tejido estructurado con paneles de malla, herrajes plateados y correas ajustables. La solapa superior oculta un cierre con cordón, mientras que la parte trasera acolchada garantiza la comodidad durante el transporte. El diseño está acentuado con una placa con el logotipo tonal y las Four sistches tan características de la Maison: lo contrario a una etiqueta."
    },
    {
        id: 27,
        tipo: "Accesorios",
        categoria: "Accesorios",
        color: ["Azul marino"],
        stock: true,
        img: ["img/inventario/accesorios/bandaparaelcuellodelanamerino1.jpg", "img/inventario/accesorios/bandaparaelcuellodelanamerino2.jpg", "img/inventario/accesorios/bandaparaelcuellodelanamerino3.jpg"],
        precio: 250,
        coleccion: "Otoño Invierno",
        nombre: "Banda para el cuello de lana merino",
        destacados: true,
        genero: "femenino",
        descripcion: "Banda para el cuello confeccionada en fina lana merino. Las Four stitches, tan emblemáticas de Maison Margiela, aparecen en la parte trasera; lo contrario a una etiqueta. "
    },
    {
        id: 28,
        tipo: "Accesorios",
        categoria: "Accesorios",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/accesorios/bufandadecachemira1.jpg", "img/inventario/accesorios/bufandadecachemira2.jpg", "img/inventario/accesorios/bufandadecachemira3.jpg"],
        precio: 650,
        coleccion: "Otoño Invierno",
        nombre: "Bufanda de cachemira",
        destacados: true,
        genero: "masculino",
        descripcion: "Minimalista y agradable al tacto a la vez, esta bufanda acanalada está confeccionada en pura cachemira para proporcionar calidez y suavidad. Sus bordes limpios y sus proporciones gráficas resaltan el juego entre la estructura y la simplicidad."
    },
    {
        id: 29,
        tipo: "Accesorios",
        categoria: "Accesorios",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/accesorios/gorrodecachemira1.jpg", "img/inventario/accesorios/gorrodecachemira2.jpg", "img/inventario/accesorios/gorrodecachemira3.jpg"],
        precio: 850,
        coleccion: "Otoño Invierno",
        nombre: "Gorro de cachemira",
        destacados: false,
        genero: "masculino",
        descripcion: "Este gorro está confeccionado en cachemira finamente hilada con un punto acanalado clásico. El borde doblado aporta un volumen sutil, mientras que la firma de Maison Margiela, las Four sistches, aparece en la parte delantera; lo contrario a una etiqueta."
    },
    {
        id: 30,
        tipo: "Accesorios",
        categoria: "Accesorios",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/accesorios/pañueloparalacabeza1.jpg", "img/inventario/accesorios/pañueloparalacabeza2.jpg", "img/inventario/accesorios/pañueloparalacabeza2.jpg"],
        precio: 550,
        coleccion: "Otoño Invierno",
        nombre: "Pañuelo para la cabeza",
        destacados: true,
        genero: "femenino",
        descripcion: "Un básico del estilo británico, el pañuelo para la cabeza combina funcionalidad y elegancia, y ha sido utilizado históricamente tanto por la realeza como por la gente del campo. Esta versión está confeccionada en tejido repelente al agua, con un corte cónico, cierre de cremallera y capucha ajustable, lo que permite llevarlo de múltiples formas. "
    },
    {
        id: 31,
        tipo: "Accesorios",
        categoria: "Accesorios",
        color: ["Negro"],
        stock: true,
        img: ["img/inventario/accesorios/snatcheddoll1.jpg", "img/inventario/accesorios/snatcheddoll2.jpg", "img/inventario/accesorios/snatcheddoll3.jpg"],
        precio: 590,
        coleccion: "Otoño Invierno",
        nombre: "Snatched doll",
        destacados: false,
        genero: "femenino",
        descripcion: "Este bolso Snatched pequeño está confeccionado en piel de becerro granulada. El bolso Snatched se presentó por primera vez en la colección Artisanal AW19. Toma su nombre del término coloquial que designa el buen aspecto y la forma arrebatada de sujetarlo. Este bolso unisex presenta una forma asimétrica inspirada en el origami. Presenta una correa de hombro tonal desmontable cruzada y un asa delantera perforada, por lo que puede llevarse como un clutch. El bolso presenta el nuevo cierre rectangular con cerradura de espejo de la Maison, adornado con el numerical logo que se desbloquea en el número 11."
    },
]